#Application Name
spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    #no se regitre como servicio en si mismo
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync