# HTTP Server
server:
  port: 5050

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yhonVillavicencio/MicroservicioStudenV2.git

  # Spring properties in case you use different profiles
  profiles:
    active: dev